spring:
  profiles:
    active: local
    include:
      - local-security
    group:
      local: local-db, oauth
      dev: dev-db, oauth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8300
