spring:
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
#  datasource:
#    url: jdbc:mysql://localhost:13307/Reservation
#    username: root
#    password: 1212
#    driver-class-name: com.mysql.cj.jdbc.Driver