#### 토큰 값 획득
GET {{local-reservation-app-url}}/token

> {%
 client.test("Validate", function () {
     client.assert(response.status === 200, "status is not 200")
     client.assert(response.contentType.mimeType === "application/json")
     client.assert(response.body.length > 0)
 })

 client.global.set("admin_jwt_token", response.body[1].jwtToken)
 client.global.set("user_jwt_token", response.body[0].jwtToken)
 %}

### 3. addCharge
POST {{local-reservation-app-url}}/charge
Content-Type: application/json
Authorization: {{admin_jwt_token}}

{
  "chargePlaceId": "createTestChargePlaceId",
  "name": "createTestName",
  "totalCount": 10,
  "currentCount": 20,
  "chargeMembership": "MEMBERSHIP"
}

> {%
client.global.set("admin_jwt_token", "Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjc2MjY5OTgxLCJleHAiOjE2NzYzOTM0Mzg0OX0.P7vqCuL-PlrTpZpfAq8zQH3JdM7m5VW3ugmO-6P-dLxk3AZlhqLoAMihhVyP_ahfralDFXW06bxT_LE1vCmzWg")
    client.assert(response.status === 201, "status is not 201")
%}

### 1. 충전소 페이징, 정렬 검색
GET {{local-reservation-app-url}}/charge?name=createTestName

> {%
    client.assert(response.status === 200, "status is not 200")
%}

### 2. getChargeByChargePlaceId
GET {{local-reservation-app-url}}/charge/createTestChargePlaceId

> {%
    client.assert(response.status === 200, "status is not 200")
%}

### 4. updateCharge
PATCH {{local-reservation-app-url}}/charge/createTestChargePlaceId
Content-Type: application/json
Authorization: {{admin_jwt_token}}

{
  "name": "updateTestName",
  "totalCount": 9,
  "currentCount": 4
}

> {%
    client.assert(response.status === 200, "status is not 200")
%}

### 5. deleteCharge
DELETE {{local-reservation-app-url}}/charge/createTestChargePlaceId
Content-Type: application/json
Authorization: {{admin_jwt_token}}

> {%
    client.assert(response.status === 204, "status is not 200")
%}